baseURL = "http://tiramisubaren.se/"
languageCode = "sv_SE"
title = "Tiramisubaren"
theme = "restaurant-hugo"

summaryLength = "7"
paginate = 6

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
URL = "css/bootstrap.min.css"
[[params.plugins.css]]
URL = "css/slick.css"
[[params.plugins.css]]
URL = "css/font-awesome.min.css"
[[params.plugins.css]]
URL = "css/animate.min.css"
[[params.plugins.css]]
URL = "css/venobox.css"
[[params.plugins.css]]
URL = "css/main.css"
[[params.plugins.css]]
URL = "css/responsive.css"

# JS Plugins
[[params.plugins.js]]
URL = "js/jquery.min.js"
[[params.plugins.js]]
URL = "js/bootstrap.min.js"
[[params.plugins.js]]
URL = "js/slick.min.js"
[[params.plugins.js]]
URL = "js/wow.min.js"
[[params.plugins.js]]
URL = "js/venobox.min.js"
[[params.plugins.js]]
URL = "js/main.js"

############################## navigation ###############################

[[menu.main]]
name = "Start"
URL = "hero-area"
weight = 1

[[menu.main]]
name = "Om oss"
URL = "about-us"
weight = 2

[[menu.main]]
name = "Blogg"
URL = "blog"
weight = 3

[[menu.main]]
name = "Meny"
URL = "price"
weight = 4

[[menu.main]]
name = "Nyheter"
URL = "subscribe"
weight = 5

[[menu.main]]
name = "Kontakta oss"
URL = "contact-us"
weight = 6


#################### default parameters ################################
[params]
logo = "images/logo.png"
# meta data
author = "Tiramisubaren"
description = "Tiramisubaren - din glassbar!"
# google analitycs ID
google_analitycs_id = "Your ID"
# copyright
copyright = "Copyright 2020 - All Rights Reserved."

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

################################### Footer ############################
[params.footer]
enable = true
contactInfoTitle = "Kontakta <span>oss</span> "
blogTitle = "Senaste <span>bloggposter</span>"
galleryTitle = "Senaste <span>bilder</span>"
socialTitle = "Följ <span>oss</span>"

############################ footer contact item
[[params.footer.contactItem]]
title="Telefon"
icon = "fa fa-phone"
content = "0761420877"

[[params.footer.contactItem]]
title="Adress"
icon = "fa fa-map-marker"
content = "Oterdahlsgatan 9B"

[[params.footer.contactItem]]
title="E-post"
icon = "fa fa-envelope"
content = "info@tiramisubaren.se"

######################### footer gallery
[[params.footer.gallery]]
image = "images/slider/slider-img-1.jpg"

[[params.footer.gallery]]
image = "images/slider/slider-img-2.jpg"

[[params.footer.gallery]]
image = "images/slider/slider-img-3.jpg"

[[params.footer.gallery]]
image = "images/slider/slider-img-4.jpg"

[[params.footer.gallery]]
image = "images/slider/slider-img-1.jpg"

[[params.footer.gallery]]
image = "images/slider/slider-img-2.jpg"

######################## Social Icon 
[[params.footer.socialLink]]
icon = "facebook"
link = "https://fb.com/tiramisubaren"

[[params.footer.socialLink]]
icon = "twitter"
link = "https://twitter.com/tiramisubaren"

[[params.footer.socialLink]]
icon = "instagram"
link = "https://www.instagram.com/tiramisubaren"